import { describe, expect, test } from "bun:test";
import {
  createLocalPluginShimSource,
  getPluginEntry,
  mergeOpenCodeConfig,
  parseOpenCodeConfig,
} from "./install";

describe("installer config merge", () => {
  test("parses JSONC with comments and trailing commas", () => {
    const config = parseOpenCodeConfig(`{
      // OpenCode plugin list
      "plugin": ["other-plugin",],
      "mcp": {
        "docs": { "url": "https://example.com//not-a-comment", },
      },
    }`);

    expect(config.plugin).toEqual(["other-plugin"]);
    expect(config.mcp).toEqual({
      docs: { url: "https://example.com//not-a-comment" },
    });
  });

  test("adds this plugin without clobbering existing config", () => {
    const merged = mergeOpenCodeConfig(
      {
        plugin: [
          "other-plugin",
          "opencode-agent-prime@0.1.0",
          "file:///tmp/opencode-agent-prime/dist/index.js",
          ["opencode-agent-prime", { name: "agent-prime" }],
        ],
        agent: {
          build: { model: "custom/build-model" },
          custom: { model: "custom/agent-model" },
        },
        lsp: false,
        mcp: {
          "codebase-memory-mcp": { command: "codebase-memory-mcp" },
        },
      },
      "opencode-agent-prime",
    );

    expect(merged.plugin).toEqual(["opencode-agent-prime", "other-plugin"]);
    expect(merged.lsp).toBe(false);
    expect(merged.mcp).toEqual({
      "codebase-memory-mcp": { command: "codebase-memory-mcp" },
    });
    expect(merged.agent?.custom).toEqual({ model: "custom/agent-model" });
    expect(merged.agent?.build).toEqual({
      model: "custom/build-model",
      disable: true,
    });
    expect(merged.agent?.plan).toEqual({ disable: true });
  });

  test("source installs rely on a generated local plugin shim", () => {
    const merged = mergeOpenCodeConfig(
      {
        plugin: [
          "",
          "other-plugin",
          "opencode-agent-prime",
          "opencode-agent-prime@0.1.0",
          ["", { name: "stale-empty-entry" }],
          "file:///tmp/opencode-agent-prime/dist/index.js",
        ],
      },
      null,
    );

    expect(merged.plugin).toEqual(["other-plugin"]);
  });

  test("generates an ESM shim that re-exports the built plugin entry", () => {
    const source = createLocalPluginShimSource(
      "D:\\opencode-agent-prime\\dist\\index.js",
    );

    expect(source).toContain("Generated by opencode-agent-prime");
    expect(source).toContain("export { default, OpenCodeAgentPrime }");
    expect(source).toContain("file:///D:/opencode-agent-prime/dist/index.js");
  });

  test("npm installs use package-name plugin entries", () => {
    const entry = getPluginEntry(
      "C:\\Users\\eda\\AppData\\Local\\npm-cache\\_npx\\123\\node_modules\\opencode-agent-prime\\dist\\cli\\index.js",
    );

    expect(entry).toBe("opencode-agent-prime");
  });
});
